apiVersion: v1
kind: Service

metadata:
  name: sonarqube-demo-service

spec:
  type: NodePort

  selector:
    app: sonarqube-demo

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
