sonar.projectKey=sonarqube-demo
sonar.projectName=sonarqube-demo
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=venv/**,__pycache__/**,*.pyc

sonar.python.version=3.12

sonar.host.url=http://localhost:9000
